### ISSUE TITLE
Look forward to the release of the training code

### ISSUE THREAD

**Issue by Lee-inso** [ViTAE-Transformer/MTP#1]
Quite leading work, the release of the training code is anticipated.

**Comment by DotWang** [comment]
@Lee-inso Thanks for your attention! These days we are preparing to export and upload model weights, then the codes will be released.

**Comment by DotWang** [comment]
@Lee-inso Hi, we have released the codes, thanks for your attention again!

**Comment by Lee-inso** [comment]
> @Lee-inso Hi, we have released the codes, thanks for your attention again!

Its glad to receive your notification. ^_^
