### ISSUE TITLE
Environment setting Question..

### ISSUE THREAD

**Issue by chartgod** [ViTAE-Transformer/MTP#11]
Hello, I'm a beginner with OpenMMLab.

I have cloned the MMEngine, MMPretrain, MMSegmentation, MMDetection, and MMRotate repositories and saved them into the MTP folder.

To install the correct version for my environment, should I use a pip command like pip install MMEngine==0.8.4? Or is there a way to set the version directly from within the repository? I'm curious to know.

**Comment by DotWang** [comment]
@chartgod you can refer to this: https://mmsegmentation.readthedocs.io/en/latest/get_started.html
