### ISSUE TITLE
关于语义分割任务的微调

### ISSUE THREAD

**Issue by NanCheng2001** [ViTAE-Transformer/MTP#12]
您好，您的MTP基础模型在语义分割数据集上进行了微调。您的微调是打开MTP的全部参数进行调整吗？有没有冻结MTP的编码器部分？仅需8W次迭代吗？

**Comment by DotWang** [comment]
@NanCheng2001 是全量微调的，没有冻结

**Comment by NanCheng2001** [comment]
感谢！
