### ISSUE TITLE
Data set Question.

### ISSUE THREAD

**Issue by chartgod** [ViTAE-Transformer/MTP#17]
Hello, may I know the name of the dataset used in the backbone network?
Change detection

**Comment by DotWang** [comment]
@chartgod For change detection, we use OSCD, WHU-CD, LEVIR, and CDD/SVCD, please see the paper.

**Comment by chartgod** [comment]
Is the bit_rvsa weight file used in the backbone network learned with that dataset?

**Comment by DotWang** [comment]
@chartgod No, we conduct the MTP on the SAMRS dataset, which does not involve change detection datasets.

**Comment by chartgod** [comment]
Thx
