### ISSUE TITLE
Installing the repo and using MMSeg

### ISSUE THREAD

**Issue by SalzingerJ** [ViTAE-Transformer/MTP#2]
Dear authors, thank you for your work and for open-sourcing it. I have a question about using this code.

I am not familiar with MMSeg, so this is probably a stupid question. I have installed it using pip but this does not install the tools folder that is needed to run the commands in the README. Should I have instead used the MMSeg repository instead of the pip package ? If yes, how do I use your repo with respect to the MMSeg repo ? It seems that MMSeg does not work like the libraries I am used to, so I am a bit confused.

Thank you in advance and good luck with your future works.

**Comment by DotWang** [comment]
@SalzingerJ Firstly, you should install the mmseg following [the official steps,](https://mmsegmentation.readthedocs.io/en/latest/get_started.html), i.e., git clone and pip install. Then, running with the provided configs, and the codes of the required models and datasets.

**Comment by DotWang** [comment]
@SalzingerJ Yeah, you can delete the *.hip files in all sub-folders, then re-compile it.

**Comment by SalzingerJ** [comment]
Dear author,

Thank you for your answer. I have made some progress and was able to compile now. I am now having a CUDA error. In your installation instructions, you do not mention the CUDA version you are using. I am pretty sure that I am using all package versions as instructed. I double checked all these versions :
- python 3.8.17
- pytorch 1.10.0
- torchvision 0.10.0
- timm 0.9.5
- opencv-python 4.8.0.76
- mmcv 2.0.0
- mmengine 0.8.4
- mmpretrain 1.2.0
- mmsegmentation 1.0.0
- mmdet 3.1.0
- mmrotate 1.0.0rc1
- opencd 1.1.0
Currently I am using all this with cuda 11.3, but this does not seem to be working, so either the cuda version is not correct or there is another issue.
Thanks in advance for your continued support. When we are done, I will summarise all the steps for future readers.

**Comment by DotWang** [comment]
@DotWang There was a misunderstanding. We running on a SLURM and a GPU server and we provide the settings of SLURM. However, we cannot obtain the CUDA version of SLURM, thus we have not shown it.  The CUDA 11.7 is for GPU server, where the pytorch version is 1.13.0.

**Comment by SalzingerJ** [comment]
Thank you for your answer. I will try with 1.13.0 and CUDA 11.7 then. If it does not work, I will also ask you for the versions of the other libraries on the GPU server.

**Comment by SalzingerJ** [comment]
Dear author. I was able to perform inference, so  am summarising the information below.

On a GPU server, the following setup works :
python 3.8.17
CUDA 11.7
pytorch 1.13.0
torchvision 0.14.0
timm 0.9.5
opencv-python 4.8.0.76
mmcv 2.0.0
mmengine 0.8.4
mmpretrain 1.2.0
mmsegmentation 1.0.0
mmdet 3.1.0
mmrotate 1.0.0rc1
opencd 1.1.0

mmsegmentation should be cloned from its repository, then the files from the desired use case should be copied into mmsegmentation following their paths in the MTP repo.
Then, all files containing "hip" should be removed from mmsegmentation/mmseg/models/backbones/ops_dcnv3, and this folder should be installed using pip. After doing all this, the project should be ready to work. At least, for me, performing inference using the MMSegInferencer worked.

**Comment by cassiaaaaaa** [comment]
> Dear author. I was able to perform inference, so am summarising the information below.
> 
> On a GPU server, the following setup works : python 3.8.17 CUDA 11.7 pytorch 1.13.0 torchvision 0.14.0 timm 0.9.5 opencv-python 4.8.0.76 mmcv 2.0.0 mmengine 0.8.4 mmpretrain 1.2.0 mmsegmentation 1.0.0 mmdet 3.1.0 mmrotate 1.0.0rc1 opencd 1.1.0
> 
> mmsegmentation should be cloned from its repository, then the files from the desired use case should be copied into mmsegmentation following their paths in the MTP repo. Then, all files containing "hip" should be removed from mmsegmentation/mmseg/models/backbones/ops_dcnv3, and this folder should be installed using pip. After doing all this, the project should be ready to work. At least, for me, performing inference using the MMSegInferencer worked.
> 
> Many thanks again for the help !

Sorry to bother you. I have a question about installing ops_dcnv3. Did you remove the hip folder and other files with name "_hip*"? Then you "pip install ops_dcnv3" ? It raises erros for me

**Comment by OE-jimvanoosten** [comment]
I also cannot get dcnv3 to compile. Same error. Which files should I delete exactly?

**Comment by AJMN88000643** [comment]
@cassiaaaaaa : Kindly share the steps you followed to run the model inference successfully on GPU, 

I am using Windows 10 PC, with CUDA 11.8, Python 3.8.10 - have created a virtual environment DotWang has suggested to check this  issue but still I am not able to run successfully and getting confused.  My requirement is Change Detection please refer my issue #42.
