### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by vaelaogudong** [ViTAE-Transformer/MTP#26]
ModuleNotFoundError: No module named 'opencd.engine.optimizers'
打开文件发现opencd和您的项目都没有提供optimizers文件，想问这个报错怎么解决

**Comment by DotWang** [comment]
@vaelaogudong opencd是基于openmmlab的mmseg开发的，所以需要先安装必要的库：mmcv，mmengine，mmseg

**Comment by vaelaogudong** [comment]
我已经安装过openmmlab框架，经过排查，是/RS_Tasks_Finetune/Change_Detection/opencd/registry.py的如下代码OPTIMIZERS = Registry(
    'optimizer',
    parent=MMENGINE_OPTIMIZERS,
    locations=['opencd.engine.optimizers'])
# manage optimizer wrapper
OPTIM_WRAPPERS = Registry(
    'optim_wrapper',
    parent=MMENGINE_OPTIM_WRAPPERS,
    locations=['opencd.engine.optimizers'])
# manage constructors that customize the optimization hyperparameters.
OPTIM_WRAPPER_CONSTRUCTORS = Registry(
    'optimizer wrapper constructor',
    parent=MMENGINE_OPTIM_WRAPPER_CONSTRUCTORS,
    locations=['opencd.engine.optimizers'])
locations指向错误，将其指向您提供的mmcv_custom即可

**Comment by jxhoh** [comment]
> 我已经安装过openmmlab框架，经过排查，是/RS_Tasks_Finetune/Change_Detection/opencd/registry.py的如下代码OPTIMIZERS = Registry( 'optimizer', parent=MMENGINE_OPTIMIZERS, locations=['opencd.engine.optimizers'])
> 
> # manage optimizer wrapper
> OPTIM_WRAPPERS = Registry( 'optim_wrapper', parent=MMENGINE_OPTIM_WRAPPERS, locations=['opencd.engine.optimizers'])
> 
> # manage constructors that customize the optimization hyperparameters.
> OPTIM_WRAPPER_CONSTRUCTORS = Registry( 'optimizer wrapper constructor', parent=MMENGINE_OPTIM_WRAPPER_CONSTRUCTORS, locations=['opencd.engine.optimizers']) locations指向错误，将其指向您提供的mmcv_custom即可


您好 ，我也是这里错误的，我想知道，您是怎么解决问题的

**Comment by jxhoh** [comment]
![Image](https://github.com/user-attachments/assets/72d4339c-5a8f-4344-b37b-2fc1fb335149)
我大概改成这样，不知道能不能成

**Comment by DotWang** [comment]
@vaelaogudong @jxhoh thanks for your reminder, we have uploaded the missed `opencd/engine` folder
