### ISSUE TITLE
Inference on single image

### ISSUE THREAD

**Issue by ogencoglu** [ViTAE-Transformer/MTP#28]
Is there a quick script, notebook or colab to run semantic segmentation inference with your pretrained models models on some arbitrary image that is not part of the datasets you listed?

**Comment by DotWang** [comment]
@ogencoglu What you need is an ordinary function in previous research about segmentaiton, while the slide inference for any size image is achieved by the repo of PSPNet in a very early time. Even if my code is originally borrowed from there, so all of my repos related to segmentation (except openmmlab-based) may contain it, such as samrs, dcn-t, etc.

**Comment by DotWang** [comment]
@ogencoglu maybe this your need

https://github.com/ViTAE-Transformer/SAMRS/blob/main/Pretraining%20and%20Finetuning/Encoder_Decoder/test_gpu.py

or you can use the mmsegmentation

**Comment by ogencoglu** [comment]
Thanks!
