### ISSUE TITLE
How to inference on custom dataset?

### ISSUE THREAD

**Issue by HalvesChen** [ViTAE-Transformer/MTP#5]
Hello, thanks for your amazing job.
I want to use Semantic Segmentation model finetuned on LoveDA, but it seems that there is no script for inference on custom dataset provided here.
How should I do it?

**Comment by DotWang** [comment]
@HalvesChen mmseg can be used for inference, and we have provided related training and inference commands in README. Before this, you should prepare your dataset as the requirement of mmseg.

**Comment by SalzingerJ** [comment]
@HalvesChen If that can be useful, I have performed inference based on the author's recommendations in this issue, and left a message at the end to summarise the learnings : https://github.com/ViTAE-Transformer/MTP/issues/2

**Comment by HalvesChen** [comment]
> @HalvesChen If that can be useful, I have performed inference based on the author's recommendations in this issue, and left a message at the end to summarise the learnings : #2

Thanks， your reply is helpful!
